# Generated by Django 6.0 on 2025-12-16 06:38

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
