# Generated by Django 6.0 on 2025-12-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_clubmembership_club_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembership',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('EXECUTIVE', 'Executive'), ('FOUNDER', 'Founder')], default='MEMBER', max_length=20),
        ),
    ]
