# Generated by Django 5.2.8 on 2026-03-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clubmembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmembership',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
