# Generated by Django 6.0 on 2025-12-15 12:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('UP', 'Upcoming'), ('OP', 'Open'), ('ON', 'Ongoing'), ('CL', 'Closed')], default='UP', max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
            ],
        ),
    ]
