# Generated by Django 6.0 on 2025-12-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('INP', 'In_Person'), ('ONL', 'Online')], default='INP', max_length=100),
        ),
    ]
