# Generated by Django 6.0 on 2025-12-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_jointournament_tournament_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointournament',
            name='role',
            field=models.CharField(choices=[('ORGANIZER', 'Organizer'), ('EXECUTIVE', 'Executive'), ('PARTICIPANT', 'Participant')], default='PARTICIPANT', max_length=12),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('OPEN', 'Open'), ('ONGOING', 'Ongoing'), ('CLOSED', 'Closed')], default='UPCOMING', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('IN_PERSON', 'In_Person'), ('ONLINE', 'Online')], default='IN_PERSON', max_length=100),
        ),
    ]
