# Generated by Django 6.0 on 2025-12-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_jointournament_role_alter_tournament_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('SWISS', 'Swiss'), ('ROUND_ROBIN', 'Round_Robin'), ('KNOCKOUT', 'Knockout'), ('DOUBLE_ELIMINATION', 'Double_Elimination')], default='SWISS', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REGISTRATION_OPEN', 'Registration_Open'), ('REGISTRATION_CLOSED', 'Registration_Closed'), ('ONGOING', 'Ongoing'), ('CLOSED', 'Closed')], default='DRAFT', max_length=100),
        ),
    ]
