# Generated by Django 6.0 on 2026-01-05 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_alter_tournament_options_tournamentpermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentpermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tournament',
            name='admins',
            field=models.ManyToManyField(related_name='tournament_admin_perms', through='tournaments.TournamentPermission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jointournament',
            name='role',
            field=models.CharField(choices=[('ORGANIZER', 'Organizer'), ('ADMIN', 'Admin'), ('PARTICIPANT', 'Participant')], default='PARTICIPANT', max_length=12),
        ),
        migrations.AlterField(
            model_name='tournamentpermission',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='tournaments.tournament'),
        ),
        migrations.AddConstraint(
            model_name='tournamentpermission',
            constraint=models.UniqueConstraint(fields=('user', 'tournament'), name='unique_tournament_admin'),
        ),
    ]
