# Generated by Django 6.0 on 2026-01-23 19:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_alter_tournamentpermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='random_seed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rounds',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.CreateModel(
            name='HostTournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_rounds', models.IntegerField()),
                ('current_round', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
        ),
    ]
