# Generated by Django 6.0 on 2026-01-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_participant_random_seed_tournament_rounds_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tournamentpermission',
            name='unique_tournament_admin',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='admins',
        ),
        migrations.AddField(
            model_name='participant',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rounds',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='TournamentPermission',
        ),
    ]
