# Generated by Django 6.0 on 2026-02-01 01:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_remove_tournamentpermission_unique_tournament_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosttournament',
            name='round_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hosttournament',
            name='current_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hosttournament',
            name='total_rounds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hosttournament',
            name='tournament',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('round_num', models.IntegerField(default=0)),
                ('p1_result', models.CharField(choices=[('WIN', 'Win'), ('DRAW', 'Draw'), ('LOSS', 'Loss')], default='DRAW', max_length=4)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='tournaments.participant')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='tournaments.participant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
        ),
    ]
