# Generated by Django 6.0 on 2026-02-16 19:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_match_p2_result_alter_hosttournament_current_round_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['ordering']},
        ),
        migrations.AddField(
            model_name='match',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='p1_result',
            field=models.CharField(choices=[('WIN', 'Win'), ('DRAW', 'Draw'), ('LOSS', 'Loss'), ('NONE', 'None')], default='NONE', max_length=4),
        ),
        migrations.AlterField(
            model_name='match',
            name='p2_result',
            field=models.CharField(choices=[('WIN', 'Win'), ('DRAW', 'Draw'), ('LOSS', 'Loss'), ('NONE', 'None')], default='NONE', max_length=4),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('round_num', models.IntegerField(default=1)),
                ('round_status', models.CharField(choices=[('CREATED', 'Created'), ('ONGOING', 'Ongoing'), ('FINISHED', 'Finished')], default='CREATED', max_length=8)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='round_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.round'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('tournament', 'round_num', 'player_1', 'player_2'), name='unique_round_pairing'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('tournament', 'round_num'), name='unique_tournament_round'),
        ),
    ]
