# Generated by Django 5.2.8 on 2026-03-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_alter_match_options_match_iscompleted_match_ordering_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointournament',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
