# Generated by Django 5.2.8 on 2026-03-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_alter_jointournament_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='p1_points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='match',
            name='p2_points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
