# Generated by Django 5.2.8 on 2026-03-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_match_p1_points_match_p2_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='rating',
            new_name='cfc_rating',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='points',
            new_name='total_points',
        ),
        migrations.AddField(
            model_name='participant',
            name='color_balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='color_history',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='fide_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='second_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
