# Generated by Django 5.2.8 on 2026-03-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_rename_rating_participant_cfc_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='table_number',
            field=models.IntegerField(default=0),
        ),
    ]
